name: Request a modification to your Hall Of Fame entry
description: Change your name and affiliation in the Mozilla Security Hall of Fame
title: "[Edit Request]: "
labels: ["edit-entry", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please note that modifying entries will take a big longer as the typical addition.
  - type: dropdown
    id: bug-type
    attributes:
      label: bug-type
      description: Which report type do you want to link to?
      options:
        - Bugzilla
        - Hacker One
      default: 0
    validations:
      required: true
  - type: input
    id: bug-info
    attributes:
      label: Bug Information
      description: For which bug do you want to claim an addition to our Hall of Fame?
      placeholder: ex. https://bugzilla.mozilla.org/show_bug.cgi?id=1234 or https://hackerone.com/reports/2382484
    validations:
      required: false
  - type: input
    id: reporter-name
    attributes:
      label: Your Name
      description: This name will show up on our hall of fame web page.
    validations:
      required: true
  - type: input
    id: reporter-url
    attributes:
      label: Your Homepage
      description: This URL will be used to linkify your name. Use a social profile or your personal home page.
    validations:
      required: false
  - type: input
    id: reporter-org
    attributes:
      label: Your Affiliations
      description: This name will show up after the entry, in case you want to claim group affiliation or mention your employer.
    validations:
      required: true
